#
# $Id$
#
# $Log$
# Revision 1.3  1994/09/21 22:18:44  jba
# New definitions in CONFIG* files
#
# Revision 1.2  1994/09/15  21:36:07  jba
# Mods for new CONFIG definitions
#
#

EPICS = ../../../..
include Target.include
include $(EPICS)/config/CONFIG_EXTENSIONS

DEPLIBS = $(EPICS_BASE_LIB)/libca.a $(EPICS_BASE_LIB)/libCom.a
USR_LDLIBS = -lca -lCom

CMPLR = OLD

SRCS= ../cau.c
PROD = cau

include $(EPICS)/config/RULES.Unix

